### ISSUE TITLE
Library maturity

### ISSUE THREAD

**Issue by paulocoghi** [mofm/nspctl#2]
Hello Emre Eryilmaz. Interesting approach on your library!

I would like to ask your opinion about nspctl maturity and compatibility with possible newer versions of systemd-nspawn

Thanks again!

**Comment by mofm** [comment]
Hi @paulocoghi ,

Thank you for your interest. If there is interest or a request for nspctl, I can develop it in my free time.

**Comment by paulocoghi** [comment]
Thanks for the answer!

After reading the benefits, I was just considering using it instead of machinectl, but I was in doubt about its maturity.

I'm now encouraged to use it! Thanks!
